### PR TITLE
no need to common codec anymore

### PR DESCRIPTION
**Pull request by twillouer**
Hi,

I have some weird issue because of common codec.

it's more kiss now :)

### CODE REVIEW

**Comment by twillouer** [comment]
Hello,

can you take a look ?

**Comment by twillouer** [comment]
Hello,

any news ?

**Comment by hengyunabc** [comment]
This commit has been merged into develop.

**Comment by twillouer** [comment]
hi,

can you release the version ?

**Comment by hengyunabc** [comment]
@twillouer 

```xml
<dependency>
    <groupId>io.github.hengyunabc</groupId>
    <artifactId>zabbix-sender</artifactId>
    <version>0.0.5</version>
</dependency>
```

**Comment by twillouer** [comment]
Thanks !

**Pull request merged**
